name: Confirm Cache State and Update if Needed
description: "Stores or refreshes the cache if it does not exist or is outdated, caching the current node_modules directory and updating the cache key."
author: Harrier Team

runs:
  using: "composite"
  steps:
    - name: Run Cache Store Script
      run: ./harrier-cache-store.sh
      shell: bash
