name: Confirm state of cache and update as needed
description: If cache does not exist or is outdated, cache current node_modules directory and update cache key
runs:
  using: "composite"
  steps:
    - name: Set GitHub Path
      run: echo "$GITHUB_ACTION_PATH" >> $GITHUB_PATH
      shell: bash
      env:
        GITHUB_ACTION_PATH: ${{ github.action_path }}
    - name: Retrieve latest cache of dependencies, if cache exists and is valid
      run: harrier-cache-load.sh
      shell: bash
      
